import { Router } from "express";
import { getAuth, clerkClient } from "@clerk/express";
import { db, usersTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import crypto from "crypto";
import { z } from "zod/v4";
import { rateLimit } from "../lib/auth-helpers";

const router = Router();

const CLIENT_ID = process.env.TWITCH_CLIENT_ID ?? "";
const CLIENT_SECRET = process.env.TWITCH_CLIENT_SECRET ?? "";
const REDIRECT_URI = process.env.TWITCH_REDIRECT_URI ?? "";
const SESSION_SECRET = process.env.SESSION_SECRET ?? "";

// HMAC-signed state so the callback can prove it was generated by us for
// this specific Clerk user. The previous flow encoded the userId in plain
// base64, so anyone could craft a callback URL impersonating any user and
// the route would happily bind the resulting Twitch tokens to them.
function signState(clerkUserId: string): string {
  const exp = Date.now() + 10 * 60 * 1000; // 10 min — enough for the OAuth round-trip
  const nonce = crypto.randomBytes(8).toString("hex");
  const payload = `${clerkUserId}.${exp}.${nonce}`;
  const sig = crypto.createHmac("sha256", SESSION_SECRET).update(payload).digest("hex");
  return Buffer.from(`${payload}.${sig}`).toString("base64url");
}

function verifyState(state: string): string | null {
  if (!SESSION_SECRET) return null; // fail closed — see steam.ts for the same logic
  try {
    const decoded = Buffer.from(state, "base64url").toString("utf8");
    const parts = decoded.split(".");
    if (parts.length !== 4) return null;
    const [clerkUserId, expStr, nonce, sig] = parts as [string, string, string, string];
    const exp = Number(expStr);
    if (!Number.isFinite(exp) || Date.now() > exp) return null;
    const expected = crypto
      .createHmac("sha256", SESSION_SECRET)
      .update(`${clerkUserId}.${expStr}.${nonce}`)
      .digest("hex");
    if (sig.length !== expected.length) return null;
    if (!crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) return null;
    return clerkUserId;
  } catch {
    return null;
  }
}

function buildTwitchAuthUrl(clerkUserId: string): string {
  const state = signState(clerkUserId);
  // moderator:read:followers — follow dates in the Community page
  // channel:read:subscriptions — sub tier in the Community page
  const scopes = "chat:read chat:edit channel:manage:broadcast moderator:read:followers channel:read:subscriptions";
  const url = new URL("https://id.twitch.tv/oauth2/authorize");
  url.searchParams.set("client_id", CLIENT_ID);
  url.searchParams.set("redirect_uri", REDIRECT_URI);
  url.searchParams.set("response_type", "code");
  url.searchParams.set("scope", scopes);
  url.searchParams.set("state", state);
  return url.toString();
}

// Step 1 — return the Twitch OAuth URL the frontend should send the user to.
// We *return JSON* rather than `res.redirect()` because the previous flow
// triggered the redirect from a top-level `<a href>`, which doesn't carry
// the Clerk Bearer token; Clerk's session cookie isn't reliably set on the
// API origin under the proxy setup, so the route would 401 and the button
// silently did nothing for users. Frontend now does
// `authedFetch('/api/auth/twitch')` then `window.location.assign(url)`.
router.get("/auth/twitch", (req, res) => {
  const { userId } = getAuth(req);
  if (!userId) { res.status(401).json({ error: "Unauthorized" }); return; }
  if (!SESSION_SECRET) {
    res.status(500).json({ error: "SESSION_SECRET is not configured." });
    return;
  }
  if (!CLIENT_ID || !REDIRECT_URI) {
    res.status(500).json({ error: "Twitch OAuth is not configured (missing TWITCH_CLIENT_ID / TWITCH_REDIRECT_URI)." });
    return;
  }
  // Per-user throttle so a buggy/click-happy frontend can't burst us into
  // Twitch's rate limits.
  if (!rateLimit(`twitch-init:${userId}`, { max: 10, windowMs: 60_000 })) {
    res.status(429).json({ error: "Too many requests. Slow down." });
    return;
  }
  res.json({ url: buildTwitchAuthUrl(userId) });
});

// Step 2 — Twitch redirects back here
router.get("/auth/twitch/callback", async (req, res) => {
  const { code, state } = req.query as Record<string, string>;
  if (!code || !state) { res.status(400).send("Missing code or state"); return; }

  const clerkUserId = verifyState(state);
  if (!clerkUserId) {
    res.status(400).send("Invalid or expired state — please retry the connect flow.");
    return;
  }

  // Exchange code for token
  const tokenRes = await fetch("https://id.twitch.tv/oauth2/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      client_id: CLIENT_ID,
      client_secret: CLIENT_SECRET,
      code,
      grant_type: "authorization_code",
      redirect_uri: REDIRECT_URI,
    }),
  });

  if (!tokenRes.ok) {
    res.status(500).send("Failed to exchange token");
    return;
  }

  const tokenData = (await tokenRes.json()) as { access_token: string; refresh_token: string };

  // Get Twitch user info
  const userRes = await fetch("https://api.twitch.tv/helix/users", {
    headers: {
      Authorization: `Bearer ${tokenData.access_token}`,
      "Client-Id": CLIENT_ID,
    },
  });

  const userData = (await userRes.json()) as { data: Array<{ id: string; login: string }> };
  const twitchUser = userData.data[0];
  if (!twitchUser) { res.status(500).send("Failed to fetch Twitch user"); return; }

  // Upsert user record
  const [existing] = await db.select().from(usersTable).where(eq(usersTable.clerkUserId, clerkUserId)).limit(1);
  if (existing) {
    await db.update(usersTable).set({
      twitchUserId: twitchUser.id,
      twitchUsername: twitchUser.login,
      twitchAccessToken: tokenData.access_token,
      twitchRefreshToken: tokenData.refresh_token,
    }).where(eq(usersTable.clerkUserId, clerkUserId));
  } else {
    await db.insert(usersTable).values({
      clerkUserId,
      twitchUserId: twitchUser.id,
      twitchUsername: twitchUser.login,
      twitchAccessToken: tokenData.access_token,
      twitchRefreshToken: tokenData.refresh_token,
    });
  }

  // Refresh the chat-side custom-command cache so any commands the user
  // created BEFORE linking Twitch start firing on their channel without
  // requiring a server restart. The cache loader skips owner rows whose
  // `twitchUsername` is null — linking populates it, so we re-key here.
  // Also dynamically `JOIN` the bot into the streamer's chat so they
  // get value from their first session without waiting on a redeploy —
  // this is what makes multi-tenant signup actually work end-to-end.
  try {
    const { reloadCustomCommands, joinChannel } = await import("../bot/bot-service");
    await reloadCustomCommands();
    await joinChannel(twitchUser.login);
  } catch (err) {
    req.log.warn({ err }, "Failed to refresh bot state after Twitch link");
  }

  // Redirect back to the channel tab so the user lands on the binding card.
  const domains = (process.env.REPLIT_DOMAINS ?? "").split(",");
  const host = domains[0] ?? "localhost";
  res.redirect(`https://${host}/account?tab=channel&connected=twitch`);
});

/**
 * POST /auth/admin-bypass — Issues a Clerk sign-in ticket for any user
 * who (a) presents the global override code and (b) is flagged isAdmin or
 * isStaff in the DB. Works in ALL environments — the admin/staff gate is the
 * security boundary; NODE_ENV is irrelevant here. Rate-limited per-IP.
 */
const AdminBypassBody = z.object({
  email: z.string().trim().min(1).max(254),
  code: z.string().trim().min(1).max(32),
});

const ADMIN_BYPASS_CODE = "424242";

router.post("/auth/admin-bypass", async (req, res) => {
  if (!rateLimit(`admin-bypass:${req.ip ?? "unknown"}`, { max: 10, windowMs: 60_000 })) {
    res.status(429).json({ error: "Too many attempts" });
    return;
  }
  const parsed = AdminBypassBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: "Invalid body" });
    return;
  }
  if (parsed.data.code !== ADMIN_BYPASS_CODE) {
    res.status(401).json({ error: "Invalid override code" });
    return;
  }
  const email = parsed.data.email.toLowerCase();
  try {
    const list = await clerkClient.users.getUserList({ emailAddress: [email], limit: 1 });
    const clerkUser = list.data[0];
    if (!clerkUser) {
      res.status(404).json({ error: "No user with that email." });
      return;
    }
    // Must be admin or staff in our DB to qualify for the bypass.
    const [dbUser] = await db
      .select({ isAdmin: usersTable.isAdmin, isStaff: usersTable.isStaff })
      .from(usersTable)
      .where(eq(usersTable.clerkUserId, clerkUser.id))
      .limit(1);
    if (!dbUser || (!dbUser.isAdmin && !dbUser.isStaff)) {
      res.status(401).json({ error: "Account is not authorised for bypass." });
      return;
    }
    const token = await clerkClient.signInTokens.createSignInToken({
      userId: clerkUser.id,
      expiresInSeconds: 300,
    });
    res.json({ ticket: token.token });
  } catch (err) {
    const errMessage = err instanceof Error ? err.message : "Unknown error";
    req.log.warn({ errMessage }, "admin-bypass: failed to mint ticket");
    res.status(500).json({ error: "Failed to mint bypass ticket" });
  }
});

/**
 * POST /auth/dev-sign-in — DEV-ONLY shortcut that issues a Clerk
 * sign-in ticket for the requested email so QA can hop into the
 * dashboard without going through Clerk's email-OTP / new-device
 * verification flows.
 *
 * Hard-gated to `NODE_ENV !== "production"` so this endpoint literally
 * does not exist on the published app — even an attacker who knew the
 * URL would get a 404. Rate-limited per-IP to make brute-forcing email
 * addresses noisy. Returns `{ ticket }` which the frontend exchanges
 * via `signIn.create({ strategy: "ticket", ticket })`.
 */
const DevSignInBody = z.object({ email: z.string().trim().min(1).max(254) });

router.post("/auth/dev-sign-in", async (req, res) => {
  // Defense-in-depth: BOTH gates must hold. NODE_ENV alone is fragile if a
  // production host is ever misconfigured to run in dev mode (architect
  // review caveat) — `ENABLE_DEV_SIGN_IN` must be explicitly opted-in too.
  // Default-closed: any other value (unset, "false", "0", etc.) → 404.
  const devEnabled =
    process.env.NODE_ENV !== "production" &&
    process.env.ENABLE_DEV_SIGN_IN === "true";
  if (!devEnabled) {
    res.status(404).json({ error: "Not found" });
    return;
  }
  if (!rateLimit(`dev-sign-in:${req.ip ?? "unknown"}`, { max: 10, windowMs: 60_000 })) {
    res.status(429).json({ error: "Too many attempts" });
    return;
  }
  const parsed = DevSignInBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: "Invalid body" });
    return;
  }
  const email = parsed.data.email.toLowerCase();
  try {
    // Clerk's `getUserList({ emailAddress })` is the supported lookup
    // path. We then mint a sign-in token bound to that user id; the
    // token is single-use and short-lived (default 30d, we cap to 5m).
    const list = await clerkClient.users.getUserList({ emailAddress: [email], limit: 1 });
    const user = list.data[0];
    if (!user) {
      res.status(404).json({ error: "No user with that email." });
      return;
    }
    const token = await clerkClient.signInTokens.createSignInToken({
      userId: user.id,
      expiresInSeconds: 300,
    });
    res.json({ ticket: token.token });
  } catch (err) {
    const errMessage = err instanceof Error ? err.message : "Unknown error";
    req.log.warn({ errMessage }, "dev-sign-in: failed to mint ticket");
    res.status(500).json({ error: "Failed to mint dev ticket" });
  }
});

export default router;
