import { Router } from "express";
import { getAuth } from "@clerk/express";
import { db, usersTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import crypto from "crypto";
import { rateLimit } from "../lib/auth-helpers";

const router = Router();

const CLIENT_ID = process.env.TWITCH_CLIENT_ID ?? "";
const CLIENT_SECRET = process.env.TWITCH_CLIENT_SECRET ?? "";
const REDIRECT_URI = process.env.TWITCH_REDIRECT_URI ?? "";
const SESSION_SECRET = process.env.SESSION_SECRET ?? "";

// HMAC-signed state so the callback can prove it was generated by us for
// this specific Clerk user. The previous flow encoded the userId in plain
// base64, so anyone could craft a callback URL impersonating any user and
// the route would happily bind the resulting Twitch tokens to them.
function signState(clerkUserId: string): string {
  const exp = Date.now() + 10 * 60 * 1000; // 10 min — enough for the OAuth round-trip
  const nonce = crypto.randomBytes(8).toString("hex");
  const payload = `${clerkUserId}.${exp}.${nonce}`;
  const sig = crypto.createHmac("sha256", SESSION_SECRET).update(payload).digest("hex");
  return Buffer.from(`${payload}.${sig}`).toString("base64url");
}

function verifyState(state: string): string | null {
  if (!SESSION_SECRET) return null; // fail closed — see steam.ts for the same logic
  try {
    const decoded = Buffer.from(state, "base64url").toString("utf8");
    const parts = decoded.split(".");
    if (parts.length !== 4) return null;
    const [clerkUserId, expStr, nonce, sig] = parts as [string, string, string, string];
    const exp = Number(expStr);
    if (!Number.isFinite(exp) || Date.now() > exp) return null;
    const expected = crypto
      .createHmac("sha256", SESSION_SECRET)
      .update(`${clerkUserId}.${expStr}.${nonce}`)
      .digest("hex");
    if (sig.length !== expected.length) return null;
    if (!crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) return null;
    return clerkUserId;
  } catch {
    return null;
  }
}

function buildTwitchAuthUrl(clerkUserId: string): string {
  const state = signState(clerkUserId);
  const scopes = "chat:read chat:edit channel:manage:broadcast";
  const url = new URL("https://id.twitch.tv/oauth2/authorize");
  url.searchParams.set("client_id", CLIENT_ID);
  url.searchParams.set("redirect_uri", REDIRECT_URI);
  url.searchParams.set("response_type", "code");
  url.searchParams.set("scope", scopes);
  url.searchParams.set("state", state);
  return url.toString();
}

// Step 1 — return the Twitch OAuth URL the frontend should send the user to.
// We *return JSON* rather than `res.redirect()` because the previous flow
// triggered the redirect from a top-level `<a href>`, which doesn't carry
// the Clerk Bearer token; Clerk's session cookie isn't reliably set on the
// API origin under the proxy setup, so the route would 401 and the button
// silently did nothing for users. Frontend now does
// `authedFetch('/api/auth/twitch')` then `window.location.assign(url)`.
router.get("/auth/twitch", (req, res) => {
  const { userId } = getAuth(req);
  if (!userId) { res.status(401).json({ error: "Unauthorized" }); return; }
  if (!SESSION_SECRET) {
    res.status(500).json({ error: "SESSION_SECRET is not configured." });
    return;
  }
  if (!CLIENT_ID || !REDIRECT_URI) {
    res.status(500).json({ error: "Twitch OAuth is not configured (missing TWITCH_CLIENT_ID / TWITCH_REDIRECT_URI)." });
    return;
  }
  // Per-user throttle so a buggy/click-happy frontend can't burst us into
  // Twitch's rate limits.
  if (!rateLimit(`twitch-init:${userId}`, { max: 10, windowMs: 60_000 })) {
    res.status(429).json({ error: "Too many requests. Slow down." });
    return;
  }
  res.json({ url: buildTwitchAuthUrl(userId) });
});

// Step 2 — Twitch redirects back here
router.get("/auth/twitch/callback", async (req, res) => {
  const { code, state } = req.query as Record<string, string>;
  if (!code || !state) { res.status(400).send("Missing code or state"); return; }

  const clerkUserId = verifyState(state);
  if (!clerkUserId) {
    res.status(400).send("Invalid or expired state — please retry the connect flow.");
    return;
  }

  // Exchange code for token
  const tokenRes = await fetch("https://id.twitch.tv/oauth2/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      client_id: CLIENT_ID,
      client_secret: CLIENT_SECRET,
      code,
      grant_type: "authorization_code",
      redirect_uri: REDIRECT_URI,
    }),
  });

  if (!tokenRes.ok) {
    res.status(500).send("Failed to exchange token");
    return;
  }

  const tokenData = (await tokenRes.json()) as { access_token: string; refresh_token: string };

  // Get Twitch user info
  const userRes = await fetch("https://api.twitch.tv/helix/users", {
    headers: {
      Authorization: `Bearer ${tokenData.access_token}`,
      "Client-Id": CLIENT_ID,
    },
  });

  const userData = (await userRes.json()) as { data: Array<{ id: string; login: string }> };
  const twitchUser = userData.data[0];
  if (!twitchUser) { res.status(500).send("Failed to fetch Twitch user"); return; }

  // Upsert user record
  const [existing] = await db.select().from(usersTable).where(eq(usersTable.clerkUserId, clerkUserId)).limit(1);
  if (existing) {
    await db.update(usersTable).set({
      twitchUserId: twitchUser.id,
      twitchUsername: twitchUser.login,
      twitchAccessToken: tokenData.access_token,
      twitchRefreshToken: tokenData.refresh_token,
    }).where(eq(usersTable.clerkUserId, clerkUserId));
  } else {
    await db.insert(usersTable).values({
      clerkUserId,
      twitchUserId: twitchUser.id,
      twitchUsername: twitchUser.login,
      twitchAccessToken: tokenData.access_token,
      twitchRefreshToken: tokenData.refresh_token,
    });
  }

  // Redirect back to the channel tab so the user lands on the binding card.
  const domains = (process.env.REPLIT_DOMAINS ?? "").split(",");
  const host = domains[0] ?? "localhost";
  res.redirect(`https://${host}/account?tab=channel&connected=twitch`);
});

export default router;
