import { Router } from "express";
import { getAuth, clerkClient } from "@clerk/express";
import { db, usersTable } from "@workspace/db";
import { eq } from "drizzle-orm";
import crypto from "crypto";
import { z } from "zod/v4";
import { rateLimit } from "../lib/auth-helpers";

const router = Router();

const CLIENT_ID = process.env.TWITCH_CLIENT_ID ?? "";
const CLIENT_SECRET = process.env.TWITCH_CLIENT_SECRET ?? "";
const REDIRECT_URI = process.env.TWITCH_REDIRECT_URI ?? "";
const SESSION_SECRET = process.env.SESSION_SECRET ?? "";

// HMAC-signed state so the callback can prove it was generated by us for
// this specific Clerk user. The previous flow encoded the userId in plain
// base64, so anyone could craft a callback URL impersonating any user and
// the route would happily bind the resulting Twitch tokens to them.
function signState(clerkUserId: string): string {
  const exp = Date.now() + 10 * 60 * 1000; // 10 min — enough for the OAuth round-trip
  const nonce = crypto.randomBytes(8).toString("hex");
  const payload = `${clerkUserId}.${exp}.${nonce}`;
  const sig = crypto.createHmac("sha256", SESSION_SECRET).update(payload).digest("hex");
  return Buffer.from(`${payload}.${sig}`).toString("base64url");
}

function verifyState(state: string): string | null {
  if (!SESSION_SECRET) return null; // fail closed — see steam.ts for the same logic
  try {
    const decoded = Buffer.from(state, "base64url").toString("utf8");
    const parts = decoded.split(".");
    if (parts.length !== 4) return null;
    const [clerkUserId, expStr, nonce, sig] = parts as [string, string, string, string];
    const exp = Number(expStr);
    if (!Number.isFinite(exp) || Date.now() > exp) return null;
    const expected = crypto
      .createHmac("sha256", SESSION_SECRET)
      .update(`${clerkUserId}.${expStr}.${nonce}`)
      .digest("hex");
    if (sig.length !== expected.length) return null;
    if (!crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) return null;
    return clerkUserId;
  } catch {
    return null;
  }
}

function buildTwitchAuthUrl(clerkUserId: string): string {
  const state = signState(clerkUserId);
  const scopes = "chat:read chat:edit channel:manage:broadcast";
  const url = new URL("https://id.twitch.tv/oauth2/authorize");
  url.searchParams.set("client_id", CLIENT_ID);
  url.searchParams.set("redirect_uri", REDIRECT_URI);
  url.searchParams.set("response_type", "code");
  url.searchParams.set("scope", scopes);
  url.searchParams.set("state", state);
  return url.toString();
}

// Step 1 — return the Twitch OAuth URL the frontend should send the user to.
// We *return JSON* rather than `res.redirect()` because the previous flow
// triggered the redirect from a top-level `<a href>`, which doesn't carry
// the Clerk Bearer token; Clerk's session cookie isn't reliably set on the
// API origin under the proxy setup, so the route would 401 and the button
// silently did nothing for users. Frontend now does
// `authedFetch('/api/auth/twitch')` then `window.location.assign(url)`.
router.get("/auth/twitch", (req, res) => {
  const { userId } = getAuth(req);
  if (!userId) { res.status(401).json({ error: "Unauthorized" }); return; }
  if (!SESSION_SECRET) {
    res.status(500).json({ error: "SESSION_SECRET is not configured." });
    return;
  }
  if (!CLIENT_ID || !REDIRECT_URI) {
    res.status(500).json({ error: "Twitch OAuth is not configured (missing TWITCH_CLIENT_ID / TWITCH_REDIRECT_URI)." });
    return;
  }
  // Per-user throttle so a buggy/click-happy frontend can't burst us into
  // Twitch's rate limits.
  if (!rateLimit(`twitch-init:${userId}`, { max: 10, windowMs: 60_000 })) {
    res.status(429).json({ error: "Too many requests. Slow down." });
    return;
  }
  res.json({ url: buildTwitchAuthUrl(userId) });
});

// Step 2 — Twitch redirects back here
router.get("/auth/twitch/callback", async (req, res) => {
  const { code, state } = req.query as Record<string, string>;
  if (!code || !state) { res.status(400).send("Missing code or state"); return; }

  const clerkUserId = verifyState(state);
  if (!clerkUserId) {
    res.status(400).send("Invalid or expired state — please retry the connect flow.");
    return;
  }

  // Exchange code for token
  const tokenRes = await fetch("https://id.twitch.tv/oauth2/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      client_id: CLIENT_ID,
      client_secret: CLIENT_SECRET,
      code,
      grant_type: "authorization_code",
      redirect_uri: REDIRECT_URI,
    }),
  });

  if (!tokenRes.ok) {
    res.status(500).send("Failed to exchange token");
    return;
  }

  const tokenData = (await tokenRes.json()) as { access_token: string; refresh_token: string };

  // Get Twitch user info
  const userRes = await fetch("https://api.twitch.tv/helix/users", {
    headers: {
      Authorization: `Bearer ${tokenData.access_token}`,
      "Client-Id": CLIENT_ID,
    },
  });

  const userData = (await userRes.json()) as { data: Array<{ id: string; login: string }> };
  const twitchUser = userData.data[0];
  if (!twitchUser) { res.status(500).send("Failed to fetch Twitch user"); return; }

  // Upsert user record
  const [existing] = await db.select().from(usersTable).where(eq(usersTable.clerkUserId, clerkUserId)).limit(1);
  if (existing) {
    await db.update(usersTable).set({
      twitchUserId: twitchUser.id,
      twitchUsername: twitchUser.login,
      twitchAccessToken: tokenData.access_token,
      twitchRefreshToken: tokenData.refresh_token,
    }).where(eq(usersTable.clerkUserId, clerkUserId));
  } else {
    await db.insert(usersTable).values({
      clerkUserId,
      twitchUserId: twitchUser.id,
      twitchUsername: twitchUser.login,
      twitchAccessToken: tokenData.access_token,
      twitchRefreshToken: tokenData.refresh_token,
    });
  }

  // Refresh the chat-side custom-command cache so any commands the user
  // created BEFORE linking Twitch start firing on their channel without
  // requiring a server restart. The cache loader skips owner rows whose
  // `twitchUsername` is null — linking populates it, so we re-key here.
  // Also dynamically `JOIN` the bot into the streamer's chat so they
  // get value from their first session without waiting on a redeploy —
  // this is what makes multi-tenant signup actually work end-to-end.
  try {
    const { reloadCustomCommands, joinChannel } = await import("../bot/bot-service");
    await reloadCustomCommands();
    await joinChannel(twitchUser.login);
  } catch (err) {
    req.log.warn({ err }, "Failed to refresh bot state after Twitch link");
  }

  // Redirect back to the channel tab so the user lands on the binding card.
  const domains = (process.env.REPLIT_DOMAINS ?? "").split(",");
  const host = domains[0] ?? "localhost";
  res.redirect(`https://${host}/account?tab=channel&connected=twitch`);
});

// ──────────────────────────────────────────────────────────────────────────
// Dev/admin breach-check bypass
//
// Replit-managed Clerk has "Reject compromised passwords on sign-in" turned
// on at the instance level, which we can't toggle. When a dev/admin account
// (whose mailbox is fake) tries to sign in with a known-pwned password,
// Clerk forces a password reset email — which never arrives.
//
// This endpoint clears the `password_compromised` flag on Clerk so the next
// sign-in attempt succeeds. It's gated by:
//   1. Verifying the caller actually knows the account password (Clerk's
//      `users.verifyPassword`), so a random attacker can't unlock anyone.
//   2. The DB row must have `isDev || isAdmin`. Plain users still go
//      through the breach reset flow.
//
// Returns generic 401s on any failure (wrong password, no such user, not
// dev/admin) so the endpoint can't be used to enumerate accounts.
// ──────────────────────────────────────────────────────────────────────────

const BypassBody = z.object({
  email: z.string().email().max(254),
  password: z.string().min(1).max(256),
});

router.post("/dev-bypass-pwned", async (req, res) => {
  // Per-IP rate limit — this endpoint takes a raw password, so we throttle
  // hard to make brute-forcing the dev-account list expensive.
  const ip = req.ip ?? req.socket.remoteAddress ?? "unknown";
  if (!rateLimit(`dev-bypass:${ip}`, { max: 5, windowMs: 60_000 })) {
    res.status(429).json({ error: "Too many attempts. Try again in a minute." });
    return;
  }

  const parsed = BypassBody.safeParse(req.body);
  if (!parsed.success) {
    res.status(400).json({ error: "Invalid body", issues: parsed.error.issues });
    return;
  }
  const { email, password } = parsed.data;

  // Generic 401 helper — every failure mode looks identical to the caller
  // so this route can't be used to enumerate emails or dev-account status.
  const deny = () => res.status(401).json({ error: "Unable to bypass for this account." });

  try {
    const list = await clerkClient.users.getUserList({ emailAddress: [email], limit: 2 });
    if (list.totalCount !== 1) {
      deny();
      return;
    }
    const cu = list.data[0]!;

    // Confirm password ownership BEFORE we touch any flags.
    try {
      await clerkClient.users.verifyPassword({ userId: cu.id, password });
    } catch {
      deny();
      return;
    }

    // Must be a dev/admin account in our DB. We never expose this for
    // regular users — they get the proper reset-email flow.
    const [row] = await db
      .select({ isDev: usersTable.isDev, isAdmin: usersTable.isAdmin })
      .from(usersTable)
      .where(eq(usersTable.clerkUserId, cu.id))
      .limit(1);
    if (!row || (!row.isDev && !row.isAdmin)) {
      deny();
      return;
    }

    await clerkClient.users.unsetPasswordCompromised(cu.id);
    res.json({ ok: true });
  } catch (err) {
    req.log.warn(
      { errName: (err as Error)?.name, errMessage: (err as Error)?.message },
      "dev-bypass-pwned failed",
    );
    deny();
  }
});

export default router;
